sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: IMBSIdElyd3KRCl+Esl4oTokQvFJCmdb5v3tUE2wv6hFXwJcHl8tG4O0q8GfzL79lvwuHy2JSpeVuio1yy6GB1Q/syg3Dxow1OD2Fl4nnxqKxyaKXhyBKSPcmrYSp+W4gB0pFPPgPMVOEvLerdveZlRe04hurfR5EhiVjc5l37wBHPdpytOTWEibSBErWrhG1QjX0IY0QX9gI7MqADB7CKut9BiC2Ilrw170xzYZh0uO/6i+FfhJ3heGfHUV+NYok6kkbmNSy8NO11dkbTfQRyjrariGISn6uP8sT28oPquKPKRFizQhZ7JZhCUSbTdGgWmS/HJERD2XAPvE+9qS3sD+YwmZdPzZ8SoEAsofoXS2rZjsgtNM0ny32mxFn3zbvgUSGErvHJpIhqzcAWjH9NN2eY0FGh63UYs6Kc1LknzwdlVCr1c0OPAPVlh19i0ckL0YXfaNPWVKSeZcU5AW2nS8H+/VPFtpcf/qKLZP4qi/tftwf5b8n3MOMBmipBs9iHvZUOP8LIBzFWfoDLGRu497eiY2jyoiP5mTnS/iSSph46QJYp3TKN6O02hGZySGFlg61KA+kIrqibAvIVei5I1DY5HVcaN+yg8Wp+LTHCu7nsWRyp2WHBvCbwgpSkq9nPG9WJaWwmD4PkHXLbrKRt4LxCUnkBVX4K3frw7l1gY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Dynevor-Terrace--Or-The-Clue-of-Life---Volume-1_4235
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy